import Head from "next/head";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import ProjectList from "../components/ProjectList";
import SkillList from "../components/SkillList";

import { PageInfo, Project, Skill } from "../typings";

import { fetchPageInfo } from "../utils/fetchPageInfo";
import { fetchProjects } from "../utils/fetchProjects";
import { fetchSkills } from "../utils/fetchSkills";
import type { GetStaticProps } from "next";

type Props = {
  pageInfo: PageInfo;
  skills: Skill[];
  projects: Project[];
};

const Home = ({ pageInfo, skills, projects }: Props) => {
  return (
    <div
      data-scroll-container
      className="px-5 bg-[#0a1216] text-neutral-100 tracking-wider"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero pageInfo={pageInfo} />

      <SkillList skills={skills} />
      <ProjectList projects={projects} />
      <Footer />
    </div>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo = await fetchPageInfo();
  const skills: Skill[] = await fetchSkills();
  const projects: Project[] = await fetchProjects();

  return {
    props: {
      pageInfo,
      projects,
      skills,
    },

    revalidate: 10,
  };
};

export default Home;
